version: "3.8"
services:
  web-app:
    build:
      context: .
      dockerfile: docker/Dockerfile-app
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-pgsql
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_data:

